# Generated by Django 6.0.6 on 2026-07-05 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audiocalls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="call",
            name="transcript_segments",
        ),
        migrations.AddField(
            model_name="transcriptsegment",
            name="call",
            field=models.ForeignKey(
                default="00000000-0000-0000-0000-000000000000",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcript_segments",
                to="audiocalls.call",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="transcriptionrole",
            name="end_time",
        ),
        migrations.AddField(
            model_name="transcriptionrole",
            name="end_time",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="transcriptionrole",
            name="start_time",
        ),
        migrations.AddField(
            model_name="transcriptionrole",
            name="start_time",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="transcriptsegment",
            name="end_time",
        ),
        migrations.AddField(
            model_name="transcriptsegment",
            name="end_time",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="transcriptsegment",
            name="start_time",
        ),
        migrations.AddField(
            model_name="transcriptsegment",
            name="start_time",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
